  /**:
    controller_manager:
      ros__parameters:
        update_rate: 100  # Hz

        joint_state_broadcaster:
          type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
          type: imu_sensor_broadcaster/IMUSensorBroadcaster
              
        # velocity_controller:
        #   type: velocity_controllers/JointGroupVelocityController

        diff_drive_controller:
          type: diff_drive_controller/DiffDriveController
      
    imu_sensor_broadcaster:
      ros__parameters:
        sensor_name: "imu_sensor"
        frame_id: "imu_frame"

    # velocity_controller:
    #   ros__parameters:
    #     joints:
    #       - left_wheel_joint
    #       - right_wheel_joint
    #     command_interfaces:
    #       - velocity
    #     state_interfaces:
    #       - velocity

    diff_drive_controller:
      ros__parameters:
        use_sim_time: true
        
        publish_rate: 41.2               # this is what the real MiR platform publishes (default: 50)
        update_rate: 100

        left_wheel_names: ['left_wheel_joint']
        right_wheel_names: ['right_wheel_joint']

        # These covariances are exactly what the real MiR platform publishes
        pose_covariance_diagonal : [0.00001, 0.00001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
        twist_covariance_diagonal: [0.1, 0.1, 1000000.0, 1000000.0, 1000000.0, 1000.0]
        enable_odom_tf: true

        # Wheel separation and diameter. These are both optional.
        # diff_drive_controller will attempt to read either one or both from the
        # URDF if not specified as a parameter.
        # We don't set the value here because it's different for each MiR type (100, 250, ...), and
        # the plugin figures out the correct values.
        wheel_separation : 0.445208
        wheel_radius : 0.0625

        # Wheel separation and radius multipliers
        wheel_separation_multiplier: 1.0 # default: 1.0
        wheel_radius_multiplier    : 1.0 # default: 1.0

        # Velocity commands timeout [s], default 0.5
        cmd_vel_timeout: 0.5
        use_stamped_vel: false
        allow_multiple_cmd_vel_publishers: true
        publish_cmd: false
        open_loop: false

        # frame_ids (same as real MiR platform)
        base_frame_id: base_footprint # default: base_link
        odom_frame_id: odom           # default: odom

        # Velocity and acceleration limits
        # Whenever a min_* is unspecified, default to -max_*
        linear.x.has_velocity_limits    : true
        linear.x.max_velocity           : 1.0  # m/s; move_base max_vel_x: 0.8
        linear.x.has_acceleration_limits: true
        linear.x.max_acceleration       : 2.0  # m/s^2; move_base acc_lim_x: 1.5

        angular.z.has_velocity_limits    : true
        angular.z.max_velocity           : 1.5  # rad/s; move_base max_rot_vel: 1.0
        angular.z.has_acceleration_limits: true
        angular.z.max_acceleration       : 2.5  # rad/s^2; move_base acc_lim_th: 2.0