<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="diff_controller_plugin_gazebo" params="prefix left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
    <gazebo>
      <xacro:if value="${gazebo_version == 'classic'}">
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
          <!-- <legacyMode>false</legacyMode>
          <alwaysOn>true</alwaysOn> -->
          <!-- <update_rate>60.0</update_rate> -->

          <left_joint>${left_wheel_joint}</left_joint>
          <right_joint>${right_wheel_joint}</right_joint>

          <wheel_separation>${wheel_separation}</wheel_separation>
          <wheel_diameter>${2*wheel_radius}</wheel_diameter>

          <max_wheel_torque>10</max_wheel_torque>
          <max_wheel_acceleration>2.8</max_wheel_acceleration>

          <odometry_frame>odom</odometry_frame>
          <robot_base_frame>base_footprint</robot_base_frame>

          <publish_odom>true</publish_odom>
          <publish_odom_tf>true</publish_odom_tf>
          <publish_wheel_tf>true</publish_wheel_tf>

          <!-- <topic>/model/$(arg model_name)/cmd_vel</topic>
          <odom_topic>/model/$(arg model_name)/odom</odom_topic> -->
          
        </plugin>
      </xacro:if>
      
      <xacro:if value="${gazebo_version == 'ignition'}">
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
          <left_joint>${left_wheel_joint}</left_joint>
          <right_joint>${right_wheel_joint}</right_joint>
          <!-- <wheel_separation>${wheel_separation}</wheel_separation>
          <wheel_radius>${wheel_radius}</wheel_radius> -->
          <wheel_separation>0.445</wheel_separation>
          <wheel_radius>0.06</wheel_radius>

          <max_linear_acceleration>2.0</max_linear_acceleration>
          
          <topic>/model/$(arg model_name)/cmd_vel</topic>
          <odom_topic>/model/$(arg model_name)/odom</odom_topic>
          <tf_topic>/model/$(arg model_name)/tf</tf_topic>

          <frame_id>odom</frame_id>
          <child_frame_id>base_footprint</child_frame_id>

          <odom_publish_frequency>30</odom_publish_frequency> 
          <!-- <max_linear_acceleration>2.0</max_linear_acceleration>
          <min_linear_acceleration>-2.0</min_linear_acceleration>
          <max_angular_acceleration>2.5</max_angular_acceleration>
          <min_angular_acceleration>-2.5</min_angular_acceleration>
          <max_linear_velocity>1.0</max_linear_velocity>
          <min_linear_velocity>-1.0</min_linear_velocity>
          <max_angular_velocity>1.5</max_angular_velocity>
          <min_angular_velocity>-1.5</min_angular_velocity> -->
        </plugin>
      </xacro:if>
     
    </gazebo>
  </xacro:macro>

  <xacro:macro name="set_wheel_friction" params="link friction">
    <gazebo reference="${link}">
      <mu1 value="${friction}"/>
      <mu2 value="${friction}"/>
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <minDepth>0.01</minDepth>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="set_all_wheel_frictions" params="prefix">
    <xacro:set_wheel_friction link="${prefix}left_wheel_link" friction="200"/>
    <xacro:set_wheel_friction link="${prefix}right_wheel_link" friction="200"/>
    <xacro:set_wheel_friction link="${prefix}fl_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}fr_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}bl_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}br_caster_wheel_link" friction="1"/>
  </xacro:macro>

  <xacro:macro name="p3d_base_controller" params="prefix">
    <xacro:if value="${gazebo_version == 'classic'}">
      <gazebo>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>50.0</updateRate>
          <bodyName>${prefix}base_footprint</bodyName>
          <topicName>base_pose_ground_truth</topicName>
          <gaussianNoise>0.01</gaussianNoise>
          <frameName>map</frameName>
          <xyzOffsets>0 0 0</xyzOffsets>
          <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
      </gazebo>
    </xacro:if>
    <xacro:if value="${gazebo_version == 'ignition'}">
    </xacro:if>
  </xacro:macro>
</robot>
