<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="diff_controller_plugin_gazebo" params="prefix left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
    <gazebo>
      <xacro:if value="${gazebo_version == 'classic'}">
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
          <legacyMode>false</legacyMode>
          <alwaysOn>true</alwaysOn>
          <updateRate>1000.0</updateRate>
          <leftJoint>${left_wheel_joint}</leftJoint>
          <rightJoint>${right_wheel_joint}</rightJoint>
          <wheelSeparation>${wheel_separation}</wheelSeparation>
          <wheelDiameter>${2*wheel_radius}</wheelDiameter>
          <wheelTorque>10</wheelTorque>
          <publishTf>1</publishTf>
          <odometryFrame>map</odometryFrame>
          <commandTopic>/model/$(arg model_name)/cmd_vel</commandTopic>
          <odometryTopic>/model/$(arg model_name)/odom</odometryTopic>
          <robotBaseFrame>base_footprint</robotBaseFrame>
          <wheelAcceleration>2.8</wheelAcceleration>
          <publishWheelJointState>true</publishWheelJointState>
          <publishWheelTF>false</publishWheelTF>
          <odometrySource>world</odometrySource>
          <rosDebugLevel>Debug</rosDebugLevel>
        </plugin>
      </xacro:if>
      
      <xacro:if value="${gazebo_version == 'ignition'}">
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
          <left_joint>${left_wheel_joint}</left_joint>
          <right_joint>${right_wheel_joint}</right_joint>
          <!-- <wheel_separation>${wheel_separation}</wheel_separation>
          <wheel_radius>${wheel_radius}</wheel_radius> -->
          <wheel_separation>0.445</wheel_separation>
          <wheel_radius>0.06</wheel_radius>

          <max_linear_acceleration>2.0</max_linear_acceleration>
          
          <topic>/model/$(arg model_name)/cmd_vel</topic>
          <odom_topic>/model/$(arg model_name)/odom</odom_topic>
          <tf_topic>/model/$(arg model_name)/tf</tf_topic>

          <frame_id>odom</frame_id>
          <child_frame_id>base_footprint</child_frame_id>

          <odom_publish_frequency>30</odom_publish_frequency> 
          <!-- <max_linear_acceleration>2.0</max_linear_acceleration>
          <min_linear_acceleration>-2.0</min_linear_acceleration>
          <max_angular_acceleration>2.5</max_angular_acceleration>
          <min_angular_acceleration>-2.5</min_angular_acceleration>
          <max_linear_velocity>1.0</max_linear_velocity>
          <min_linear_velocity>-1.0</min_linear_velocity>
          <max_angular_velocity>1.5</max_angular_velocity>
          <min_angular_velocity>-1.5</min_angular_velocity> -->
        </plugin>
      </xacro:if>
     
    </gazebo>
  </xacro:macro>

  <xacro:macro name="set_wheel_friction" params="link friction">
    <gazebo reference="${link}">
      <mu1 value="${friction}"/>
      <mu2 value="${friction}"/>
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <minDepth>0.01</minDepth>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="set_all_wheel_frictions" params="prefix">
    <xacro:set_wheel_friction link="${prefix}left_wheel_link" friction="200"/>
    <xacro:set_wheel_friction link="${prefix}right_wheel_link" friction="200"/>
    <xacro:set_wheel_friction link="${prefix}fl_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}fr_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}bl_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}br_caster_wheel_link" friction="1"/>
  </xacro:macro>

  <xacro:macro name="p3d_base_controller" params="prefix">
    <xacro:if value="${gazebo_version == 'classic'}">
      <gazebo>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>50.0</updateRate>
          <bodyName>${prefix}base_footprint</bodyName>
          <topicName>base_pose_ground_truth</topicName>
          <gaussianNoise>0.01</gaussianNoise>
          <frameName>map</frameName>
          <xyzOffsets>0 0 0</xyzOffsets>
          <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
      </gazebo>
    </xacro:if>
    <xacro:if value="${gazebo_version == 'ignition'}">
    </xacro:if>
  </xacro:macro>
</robot>
