/**:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz
      use_sim_time: true

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster
        filepath: /home/gilmar/Desktop/ros2_ws/src/senai_models/models/robots/mir100/config/classic/imu_sensor_broadcaster.yaml
            
      # velocity_controller:
      #   type: velocity_controllers/JointGroupVelocityController
      #   filepath: /home/gilmar/Desktop/ros2_ws/src/senai_models/models/robots/mir100/config/classic/velocity_controller.yaml

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController
        filepath: /home/gilmar/Desktop/ros2_ws/src/senai_models/models/robots/mir100/config/classic/diff_drive_controller.yaml
  




